inital commit
LTD-Beget/site pull request #2
Opened 2018-08-22 05:25 UTC by Booggmz

2018-08-22 09:03 UTC, vladqa commented on proto/v1/site.proto
> +    rpc isSiteFrozen (IsSiteFrozenRequest) returns (IsSiteFrozenResponse) {
Эти методы точно нужны отдельно?

2018-08-29 16:08 UTC, Booggmz commented on proto/v1/site.proto
> +    rpc isSiteFrozen (IsSiteFrozenRequest) returns (IsSiteFrozenResponse) {
Ты предлагаешь сделать setter? 
Не добавит ли это магии?

2018-09-05 11:19 UTC, Grey2k requested changes

2018-09-05 11:19 UTC, Grey2k commented on proto/v1/site.proto
> +    rpc isSiteFrozen (IsSiteFrozenRequest) returns (IsSiteFrozenResponse) {
Решили метод убрать и сделать отдельно getSite ()

2018-09-05 11:19 UTC, Grey2k commented on proto/v1/site.proto
> +            INVALID_NAME = 1;
SITE_ALREADY_EXIST

2018-09-05 11:19 UTC, Grey2k commented on proto/v1/structures.proto
> +message Domain {
Убрать и написать комменты

2018-09-05 12:06 UTC, Grey2k requested changes

2018-09-05 12:06 UTC, Grey2k commented on proto/v1/structures.proto
> +    string name = 6;
Поля нормально расставь и удали id

2018-09-05 13:23 UTC, Booggmz commented on proto/v1/structures.proto
> +    string name = 6;
done

2018-09-05 15:08 UTC, Grey2k approved these changes

2018-09-05 15:08 UTC, merged