refator to ID usage
LTD-Beget/site pull request #4
Opened 2018-09-13 11:18 UTC by Booggmz

2018-09-13 11:44 UTC, Grey2k requested changes

2018-09-13 11:44 UTC, Grey2k commented on proto/v1/structures.proto
> +    uint64 id = 6; // ID сайта
поменяй порядок полей

2018-09-13 11:49 UTC, Booggmz commented on proto/v1/structures.proto
> +    uint64 id = 6; // ID сайта
не допёр сразу, что оно еще не используется)) upd

2018-09-13 15:20 UTC, Grey2k approved these changes

2018-09-13 15:20 UTC, Grey2k commented on proto/v1/site.proto
>      message Success {
Здесь и рядом не нужен Succes - у тебя же не repeated

2018-09-13 15:21 UTC, Grey2k requested changes
Доделай

2018-09-14 09:43 UTC, Booggmz commented
если под "доделай" шла речь о рефакторе ансет-респонса, то доделал))

2018-09-14 10:43 UTC, Grey2k approved these changes

2018-09-14 10:43 UTC, merged